@echo off
echo Setting up Recipe API...
cd backend

echo Installing dependencies...
pip install Flask Flask-CORS

echo Processing recipe data...
python data_processor.py

echo Starting API server...
python app.py